/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import com.illposed.osc.OSCMessage;
import com.illposed.osc.OSCPortOut;
import java.io.IOException;
import java.net.InetAddress;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.Collection;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author Stefan Marks
 */
public class SoundBiteRemoteController extends javax.swing.JFrame
{
    /**
     * Creates new form SoundBiteRemoveController
     */
    public SoundBiteRemoteController()
    {
        slaves = new DefaultListModel<Slave>();
        params = new LinkedList<Object>();
        
        slaves.addElement(new Slave("localhost"));
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        chkGuiVisible = new javax.swing.JCheckBox();
        chkPaused = new javax.swing.JCheckBox();
        javax.swing.JPanel pnlSlaves = new javax.swing.JPanel();
        javax.swing.JScrollPane scrlSlaves = new javax.swing.JScrollPane();
        lstSlaves = new javax.swing.JList();
        pnlSlaveButtons = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SoundBite Remote Controller");

        chkGuiVisible.setSelected(true);
        chkGuiVisible.setText("GUI Visible:");
        chkGuiVisible.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        chkGuiVisible.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        chkGuiVisible.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                chkGuiVisibleActionPerformed(evt);
            }
        });

        chkPaused.setText("Paused:");
        chkPaused.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        chkPaused.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        chkPaused.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                chkPausedActionPerformed(evt);
            }
        });

        pnlSlaves.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("Slaves"), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        pnlSlaves.setLayout(new java.awt.BorderLayout(0, 5));

        lstSlaves.setModel(slaves);
        scrlSlaves.setViewportView(lstSlaves);

        pnlSlaves.add(scrlSlaves, java.awt.BorderLayout.CENTER);

        pnlSlaveButtons.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        btnAdd.setText("Add");
        pnlSlaveButtons.add(btnAdd);

        btnRemove.setText("Remove");
        pnlSlaveButtons.add(btnRemove);

        pnlSlaves.add(pnlSlaveButtons, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSlaves, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkGuiVisible, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkPaused, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSlaves, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkGuiVisible)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkPaused)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkGuiVisibleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chkGuiVisibleActionPerformed
    {//GEN-HEADEREND:event_chkGuiVisibleActionPerformed
        sendMessage("/enableGUI", chkGuiVisible.isSelected());
    }//GEN-LAST:event_chkGuiVisibleActionPerformed

    private void chkPausedActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_chkPausedActionPerformed
    {//GEN-HEADEREND:event_chkPausedActionPerformed
        sendMessage("/paused", chkPaused.isSelected());
    }//GEN-LAST:event_chkPausedActionPerformed

    private void sendMessage(String address, Object param1, Object param2)
    {
        params.clear();
        params.add(param1);
        params.add(param2);
        sendMessage(address, params);
    }
    
    private void sendMessage(String address, Object param1)
    {
        params.clear();
        params.add(param1);
        sendMessage(address, params);
    }

    private void sendMessage(String address, Collection<Object> parameters)
    {
        OSCMessage msg = new OSCMessage(address, parameters);
        Object[] targets = lstSlaves.getSelectedValuesList().toArray();
        if ( targets.length == 0 )
        {
            targets = slaves.toArray();
        }
        for ( Object slave : targets )
        {
            ((Slave) slave).sendMessage(msg);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                JFrame app = new SoundBiteRemoteController();
                app.setLocationRelativeTo(null);;
                app.setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRemove;
    private javax.swing.JCheckBox chkGuiVisible;
    private javax.swing.JCheckBox chkPaused;
    private javax.swing.JList lstSlaves;
    private javax.swing.JPanel pnlSlaveButtons;
    // End of variables declaration//GEN-END:variables

    private DefaultListModel<Slave>  slaves;
    private LinkedList<Object>       params;
    
    private class Slave
    {
        public Slave(String hostname)
        {
            this.address = null; 
            this.port    = null;
            try
            {
                this.address = InetAddress.getByName(hostname);
                port = new OSCPortOut(address);
            }
            catch ( UnknownHostException e )
            {
                System.err.println("Could not add slaves");
            }
            catch ( SocketException e )
            {
                System.err.println("Could not open OSC port");
            }
        }
        
        public boolean isActive()
        {
            return (port != null);
        }
        
        public void sendMessage(OSCMessage message)
        {
            try
            {
                port.send(message);
            }
            catch (IOException e)
            {
                System.err.println("Could not send message '" + message.getAddress() +
                                   "' to slave '" + address + "'");
            }
        }
        
        @Override
        public String toString()
        {
            return address.getHostAddress();
        }
        
        private InetAddress address;
        private OSCPortOut  port;
    }
}
